import Link from "next/link";
import { formatCurrency } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";
import { updateOrderStatus } from "../actions";

export default async function AdminOrdersPage() {
  const supabase = await createClient();
  const { data: orders } = await supabase.from("orders").select("id,order_number,recipient_name,payment_status,status,total_amount,shipping_charged_amount,created_at,shipments(awb_number,status)").order("created_at", { ascending: false });
  return <div><p className="eyebrow">Operasional</p><h1 className="mt-2 text-3xl font-black">Order</h1><div className="surface mt-7 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Order</th><th>Customer</th><th>Pembayaran</th><th>Ongkir final</th><th>Total</th><th>AWB</th><th>Proses</th></tr></thead><tbody className="divide-y">{orders?.map((order) => { const shipment = Array.isArray(order.shipments) ? order.shipments[0] : order.shipments; const nextStatus = order.status === "paid" ? "processing" : order.status === "processing" ? "fulfilled" : null; return <tr key={order.id}><td className="p-4"><Link className="font-black text-blue-600" href={`/account/orders/${order.id}`}>{order.order_number}</Link><p className="text-xs text-slate-400">{order.status}</p></td><td>{order.recipient_name}</td><td>{order.payment_status}</td><td className="font-bold">{formatCurrency(order.shipping_charged_amount)}</td><td>{formatCurrency(order.total_amount)}</td><td>{shipment?.awb_number ?? "—"}</td><td>{nextStatus && order.payment_status === "paid" ? <form action={updateOrderStatus} className="flex gap-2"><input type="hidden" name="order_id" value={order.id} /><input type="hidden" name="status" value={nextStatus} /><input type="hidden" name="note" value={`Status diubah admin menjadi ${nextStatus}`} /><button className="rounded-full border px-3 py-1 text-xs font-bold capitalize hover:bg-slate-50">{nextStatus}</button></form> : "—"}</td></tr>; })}</tbody></table></div></div>;
}
