<script setup lang="ts">
import type { Product,Category } from "~~/shared/types";
const props=defineProps<{product?:Product;categories:Category[]}>(); const emit=defineEmits<{saved:[id:string]}>();
const loading=ref(false);const error=ref("");const image=ref<File|null>(null);
const form=reactive({categoryId:props.product?.category.id||props.categories[0]?.id||"",name:props.product?.name||"",slug:props.product?.slug||"",shortDescription:props.product?.shortDescription||"",description:props.product?.description||"",sku:props.product?.variant.sku||"",variantName:props.product?.variant.name||"",regularPrice:props.product?.variant.regularPrice||0,salePrice:props.product?.variant.salePrice??"",stock:props.product?.variant.stockOnHand||0,weight:props.product?.variant.shippingWeightGrams||600,published:props.product?.published??true,featured:props.product?.featured??false});
async function webp(file:File){const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.8));if(!blob||blob.size>3_500_000)throw new Error("Gambar hasil optimasi melebihi 3,5 MB.");return new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.webp`,{type:"image/webp"});}
async function pick(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;error.value="";try{image.value=await webp(file);}catch(cause){error.value=cause instanceof Error?cause.message:"Gambar gagal diproses.";}}
async function save(){if(!props.categories.length){error.value="Buat minimal satu kategori sebelum menyimpan produk.";return;}loading.value=true;error.value="";try{const body=new FormData();for(const[key,value]of Object.entries(form))body.set(key,String(value));if(image.value)body.set("image",image.value);const path=props.product?`/api/admin/products/${props.product.id}`:"/api/admin/products";const result=await $fetch<{id?:string}>(path,{method:props.product?"PATCH":"POST",body});emit("saved",result.id||props.product!.id);}catch(cause:any){error.value=cause?.data?.error?.message||cause?.data?.statusMessage||"Produk gagal disimpan.";}finally{loading.value=false;}}
</script>
<template><div v-if="!categories.length" class="surface p-8 text-center"><h2 class="text-xl font-black">Kategori diperlukan</h2><p class="mt-2 text-sm text-slate-500">Buat kategori figure robot sebelum menambahkan produk.</p><NuxtLink to="/admin/products" class="mt-5 inline-block rounded-full bg-[#0b4697] px-5 py-3 text-sm font-black text-white">Kelola kategori</NuxtLink></div><form v-else class="surface grid gap-5 p-6 md:grid-cols-2" @submit.prevent="save"><label class="field-label">Nama<input v-model="form.name" class="field" required></label><label class="field-label">Slug<input v-model="form.slug" class="field" required></label><label class="field-label">Kategori<select v-model="form.categoryId" class="field"><option v-for="category in categories" :key="category.id" :value="category.id">{{category.name}}</option></select></label><label class="field-label">SKU<input v-model="form.sku" class="field" required></label><label class="field-label">Nama varian<input v-model="form.variantName" class="field" required></label><label class="field-label">Berat (gram)<input v-model.number="form.weight" type="number" class="field" required></label><label class="field-label">Harga reguler<input v-model.number="form.regularPrice" type="number" class="field" required></label><label class="field-label">Harga sale<input v-model="form.salePrice" type="number" class="field"></label><label v-if="!product" class="field-label">Stok awal<input v-model.number="form.stock" type="number" class="field"></label><label class="field-label">Gambar {{product?'baru (opsional)':'WebP otomatis'}}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" class="field" :required="!product" @change="pick"></label><label class="field-label md:col-span-2">Deskripsi singkat<input v-model="form.shortDescription" class="field"></label><label class="field-label md:col-span-2">Deskripsi<textarea v-model="form.description" class="field min-h-32"/></label><div class="flex gap-5 md:col-span-2"><label class="flex gap-2 text-sm font-bold"><input v-model="form.published" type="checkbox">Published</label><label class="flex gap-2 text-sm font-bold"><input v-model="form.featured" type="checkbox">Featured</label></div><p v-if="error" class="text-sm text-red-600 md:col-span-2">{{error}}</p><div class="md:col-span-2"><AppButton type="submit" :disabled="loading">{{loading?'Menyimpan...':'Simpan produk'}}</AppButton></div></form></template>
