<script setup lang="ts">
import { formatCurrency } from "~~/shared/format";
import { calculateCartShipping } from "~~/shared/shipping";
definePageMeta({ middleware: "auth" });
const { lines, subtotal } = useCart(); const { data } = await useFetch("/api/account/addresses");
const addressId = ref(""); const voucherCode = ref(""); const loading = ref(false); const error = ref("");
watchEffect(() => { if (!addressId.value && data.value?.addresses?.length) addressId.value = String((data.value.addresses[0] as Record<string,unknown>).id); });
const shipping = computed(() => lines.value.length ? calculateCartShipping(lines.value) : null);
async function checkout() { if (!lines.value.length || !addressId.value) return; loading.value=true; error.value=""; try { const result=await $fetch("/api/checkout",{method:"POST",body:{addressId:addressId.value,voucherCode:voucherCode.value||null,lines:lines.value.map(line=>({variantId:line.variantId,quantity:line.quantity}))}}); window.location.assign(result.payment_url); } catch (cause:any) { error.value=cause?.data?.data?.error?.message || cause?.data?.statusMessage || "Checkout gagal diproses."; loading.value=false; } }
useSeoMeta({ title: "Checkout" });
</script>
<template><section class="container-shell py-12"><p class="eyebrow">Secure checkout</p><h1 class="section-title mt-3">Checkout</h1><div v-if="!lines.length" class="surface mt-8 p-8 text-center">Keranjang kosong. <NuxtLink to="/search" class="font-bold text-[#0b4697]">Pilih produk</NuxtLink>.</div><div v-else class="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div class="grid gap-6"><section class="surface p-6"><div class="flex justify-between"><h2 class="text-xl font-black">Alamat pengiriman</h2><NuxtLink to="/account/addresses/new" class="text-sm font-bold text-[#0b4697]">Tambah alamat</NuxtLink></div><div v-if="data?.addresses?.length" class="mt-4 grid gap-3"><label v-for="address in data.addresses" :key="(address as any).id" class="flex cursor-pointer gap-3 rounded-xl border p-4"><input v-model="addressId" type="radio" :value="(address as any).id"><span><b>{{ (address as any).label }} · {{ (address as any).recipient_name }}</b><small class="mt-1 block text-slate-500">{{ (address as any).address_line }}, {{ (address as any).city }}</small></span></label></div><p v-else class="mt-4 text-sm text-slate-500">Belum ada alamat tersimpan.</p></section><section class="surface p-6"><h2 class="text-xl font-black">Voucher</h2><input v-model="voucherCode" class="field mt-4" placeholder="Kode voucher (opsional)"></section></div><aside class="surface h-fit p-6"><h2 class="text-xl font-black">Total</h2><div class="mt-5 grid gap-3 text-sm"><div class="flex justify-between"><span>Subtotal</span><b>{{ formatCurrency(subtotal) }}</b></div><div class="flex justify-between"><span>Ongkir</span><b>{{ formatCurrency(shipping?.chargedAmount || 0) }}</b></div><div class="flex justify-between border-t pt-4 text-lg"><span>Total</span><b>{{ formatCurrency(subtotal + (shipping?.chargedAmount || 0)) }}</b></div></div><AppButton class="mt-6 w-full" :disabled="loading || !addressId" @click="checkout">{{ loading ? 'Membuat QRIS...' : 'Bayar dengan QRIS' }}</AppButton><p v-if="error" class="mt-3 text-sm text-red-600">{{ error }}</p></aside></div></section></template>
