import type { Category, Product } from "@/lib/types";

export const demoCategories: Category[] = [
  {
    id: "cat-character",
    name: "Figure Karakter",
    slug: "figure-karakter",
    description: "Action figure 3D print untuk koleksi, hadiah, dan dekorasi meja.",
  },
  {
    id: "cat-chibi",
    name: "Chibi & Mini Figure",
    slug: "chibi-mini-figure",
    description: "Figure berukuran ringkas dengan karakter yang ekspresif.",
  },
  {
    id: "cat-designer",
    name: "Designer Toys",
    slug: "designer-toys",
    description: "Desk toys dan karakter orisinal dengan bentuk yang unik.",
  },
];

const makeProduct = (
  id: string,
  name: string,
  slug: string,
  category: Category,
  price: number,
  salePrice: number | null,
  stock: number,
  image: string,
  variantName: string,
  shortDescription: string,
  featured = false,
): Product => ({
  id,
  name,
  slug,
  shortDescription,
  description: `${shortDescription} Dicetak menggunakan mesin 3D, lalu diperiksa sebelum dikemas dan dikirim.`,
  category,
  images: [image],
  featured,
  published: true,
  variant: {
    id: `${id}-default`,
    productId: id,
    sku: `JWL-${id.toUpperCase()}`,
    name: variantName,
    regularPrice: price,
    salePrice,
    stockOnHand: stock,
    reservedStock: 0,
    shippingWeightGrams: 600,
  },
});

export const demoProducts: Product[] = [
  makeProduct(
    "fighter-duo",
    "Duo Fighter Arka & Bima",
    "duo-fighter-arka-bima",
    demoCategories[0],
    69_000,
    59_000,
    12,
    "/product-fighter-duo-v2.webp",
    "PLA+ • Set 2 pcs • 12 cm",
    "Set dua figure martial arts dengan warna mustard dan teal.",
    true,
  ),
  makeProduct(
    "blue-ninja",
    "Kuro Ninja Blue Chibi",
    "kuro-ninja-blue-chibi",
    demoCategories[1],
    53_000,
    42_000,
    7,
    "/product-ninja-chibi-v2.webp",
    "PLA+ • 11 cm",
    "Figure ninja chibi warna biru dengan pose bertahan.",
    true,
  ),
  makeProduct(
    "orbit-buddy",
    "Orbit Buddy Coral",
    "orbit-buddy-coral",
    demoCategories[2],
    42_000,
    37_500,
    9,
    "/product-designer-buddy-v2.webp",
    "PLA+ • 13 cm",
    "Designer desk toy dua warna dengan bentuk explorer yang ramah.",
    true,
  ),
  makeProduct(
    "pocket-rover",
    "Pocket Rover R1",
    "pocket-rover-r1",
    demoCategories[1],
    29_000,
    22_000,
    15,
    "/product-mini-robot-v2.webp",
    "PLA+ • 7 cm",
    "Mini robot bergaya retro dengan warna sage green dan sensor jingga.",
    true,
  ),
  makeProduct(
    "fighter-duo-dark",
    "Duo Fighter Arka & Bima — Dark Base",
    "duo-fighter-arka-bima-dark-base",
    demoCategories[0],
    65_000,
    null,
    6,
    "/product-fighter-duo-v2.webp",
    "PLA+ • Set 2 pcs • 12 cm",
    "Set dua figure martial arts dengan display base warna charcoal.",
  ),
  makeProduct(
    "orbit-buddy-mini",
    "Orbit Buddy Mini",
    "orbit-buddy-mini",
    demoCategories[2],
    35_000,
    null,
    10,
    "/product-designer-buddy-v2.webp",
    "PLA+ • 9 cm",
    "Versi mini desk toy Orbit Buddy untuk dekorasi meja kerja.",
  ),
];
