import { Button } from "@/components/ui/button";
import { createVoucher } from "../actions";
import { createClient } from "@/lib/supabase/server";

export default async function VouchersPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  const supabase = await createClient();
  const { data: vouchers } = await supabase.from("vouchers").select("*").order("created_at", { ascending: false });
  return <div><p className="eyebrow">Promosi produk</p><h1 className="mt-2 text-3xl font-black">Voucher</h1><form action={createVoucher} className="surface mt-7 grid gap-4 p-6 sm:grid-cols-4">{error && <p className="sm:col-span-4 text-sm text-red-600">Voucher belum dapat disimpan.</p>}<label className="field-label">Kode<input className="field uppercase" name="code" required /></label><label className="field-label">Jenis<select className="field" name="kind"><option value="fixed">Nominal</option><option value="percentage">Persen</option></select></label><label className="field-label">Nilai<input className="field" name="value" type="number" min={1} required /></label><label className="field-label">Minimum belanja<input className="field" name="minimum_spend" type="number" min={0} defaultValue={0} /></label><label className="field-label">Maks. diskon<input className="field" name="maximum_discount" type="number" min={0} /></label><label className="field-label">Kuota total<input className="field" name="usage_limit" type="number" min={1} /></label><label className="field-label">Batas/user<input className="field" name="per_user_limit" type="number" min={1} defaultValue={1} /></label><label className="field-label">Berakhir<input className="field" name="ends_at" type="datetime-local" required /></label><Button type="submit" className="sm:col-span-4 sm:w-fit">Tambah voucher</Button></form><div className="surface mt-6 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Kode</th><th>Jenis</th><th>Nilai</th><th>Berakhir</th><th>Status</th></tr></thead><tbody className="divide-y">{vouchers?.map((voucher) => <tr key={voucher.id}><td className="p-4 font-black">{voucher.code}</td><td>{voucher.kind}</td><td>{voucher.value}</td><td>{new Intl.DateTimeFormat("id-ID").format(new Date(voucher.ends_at))}</td><td>{voucher.active ? "Aktif" : "Nonaktif"}</td></tr>)}</tbody></table></div></div>;
}

