<script setup lang="ts">
import { SUPPORTED_CITIES, SUPPORTED_PROVINCES } from "~~/shared/address-regions";
definePageMeta({middleware:"auth"}); const loading=ref(false); const error=ref("");
const form=reactive({label:"Rumah",recipientName:"",phone:"",province:"DKI Jakarta",city:"Jakarta Selatan",district:"",subdistrict:"",postalCode:"",addressLine:"",landmark:"",latitude:-6.2,longitude:106.816666,isDefault:true});
const cities=computed(()=>SUPPORTED_CITIES.filter(city=>form.province==="DKI Jakarta"?city.provinceCode==="31":city.provinceCode==="36"));
async function save(){loading.value=true;error.value="";try{await $fetch("/api/account/addresses",{method:"POST",body:form});await navigateTo("/account/addresses");}catch(cause:any){error.value=cause?.data?.statusMessage||"Alamat gagal disimpan.";loading.value=false;}}
useSeoMeta({title:"Alamat Baru"});
</script>
<template><section class="container-shell py-12"><p class="eyebrow">My account</p><h1 class="section-title mt-3">Alamat baru</h1><form class="surface mt-8 grid gap-5 p-6 md:grid-cols-2" @submit.prevent="save"><label class="field-label">Label<input v-model="form.label" class="field" required></label><label class="field-label">Nama penerima<input v-model="form.recipientName" class="field" required></label><label class="field-label">Nomor telepon<input v-model="form.phone" class="field" required></label><label class="field-label">Kode pos<input v-model="form.postalCode" class="field" required></label><label class="field-label">Provinsi<select v-model="form.province" class="field"><option v-for="province in SUPPORTED_PROVINCES" :key="province.code">{{ province.name }}</option></select></label><label class="field-label">Kota<select v-model="form.city" class="field"><option v-for="city in cities" :key="city.code">{{ city.name }}</option></select></label><label class="field-label">Kecamatan<input v-model="form.district" class="field" required></label><label class="field-label">Kelurahan<input v-model="form.subdistrict" class="field" required></label><label class="field-label md:col-span-2">Alamat lengkap<textarea v-model="form.addressLine" class="field min-h-24" required/></label><label class="field-label md:col-span-2">Patokan<input v-model="form.landmark" class="field"></label><div class="md:col-span-2"><LocationPicker v-model="form"/></div><label class="flex items-center gap-2 text-sm font-bold md:col-span-2"><input v-model="form.isDefault" type="checkbox">Jadikan alamat utama</label><p v-if="error" class="text-sm text-red-600 md:col-span-2">{{error}}</p><div class="md:col-span-2"><AppButton type="submit" :disabled="loading">{{loading?'Menyimpan...':'Simpan alamat'}}</AppButton></div></form></section></template>
